service: rimac-project

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:757594104957:table/rimac-project-dev-table

  environment:
    WEATHER_API_KEY: ${env:WEATHER_API_KEY}
    SWAPI_URL: ${env:SWAPI_URL}
    WEATHER_API_URL: ${env:WEATHER_API_URL}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    CACHE_TTL: ${env:CACHE_TTL}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  fusionados:
    handler: src/handlers/fusionados.fusionados
    events:
      - http:
          path: fusionados
          method: get
          cors: true
  historial:
    handler: src/handlers/historial.historial
    events:
      - http:
          path: historial
          method: get
          cors: true
  almacenar:
    handler: src/handlers/almacenar.almacenar
    events:
      - http:
          path: almacenar
          method: post
          cors: true

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: cacheKey
            AttributeType: S
        KeySchema:
          - AttributeName: cacheKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5